### ISSUE TITLE
Anybody can change anything. No permissions 

### ISSUE THREAD

**Issue by heykevin** [CMPUT404F16Project/cmput404-project#4]

**Comment by UliceNix** [comment]
Hell yeah. More chaos! LOL but seriously which specific part were you referring to? 

What I have in mind for front-end currently is
"delete/edit posts" and "edit profile" only show the delete button when a post is authored by current user

**Comment by heykevin** [comment]
Haha pretty much everything. The ui might not allow it but everybody has access to the api. And this includes stuff like seeing friends posts. Im planning to focus on it during the weekend

**Comment by UliceNix** [comment]
Awesome! Thank you very much! Hmm maybe considering about applying for
devOps after you finish this security/authentication/authorisation and
deploying the app to openshift! Haha

**Comment by heykevin** [comment]
2 jobs for the price of one!

**Comment by UliceNix** [comment]
Fixed as permissions are now implemented. Actually it's already half done in part 1.
